### ISSUE TITLE
Getting error when installing on XenServer

### ISSUE THREAD

**Issue by syed** [NuxRo/macchinina#2]
I'm getting the following error when I try to create a VM on XenServer using this template

```
e to Task failed! Task record:                 uuid: 3f762646-8caf-3b06-7ce6-c11291822437
           nameLabel: Async.VM.start_on
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Wed Sep 07 20:23:26 CEST 2016
            finished: Wed Sep 07 20:23:27 CEST 2016
              status: failure
          residentOn: com.xensource.xenapi.Host@9a5cdeb4
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [BOOTLOADER_FAILED, OpaqueRef:da848107-a026-5f87-9777-8055948278c8, Unable to find partition containing kernel
]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []
```

Any clues?
